# Generated by Django 4.2.6 on 2024-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applylink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
