# Generated by Django 4.2.6 on 2024-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0002_job_applylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
