# Generated by Django 4.2.6 on 2024-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0003_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(),
        ),
    ]
